/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js,liquid}",
    "./sections/**/*.liquid",
    "./snippets/**/*.liquid",
    "./layout/**/*.liquid",
    "./assets/*.liquid",
  ],
  safelist: [
    {
      pattern: /^(?!(?:scroll|bottom)$)m\w?-/,
      variants: ["sm", "md", "lg", "xl", "2xl", "3xl"],
    },
    {
      pattern: /^(?!(?:scroll|bottom)$)p\w?-/,
      variants: ["sm", "md", "lg", "xl", "2xl", "3xl"],
    },
    "lg:mt-[44px]",
    "lg:mt-[56px]",
    "lg:mb-[38px]",
    "mt-[32px]",
    "mb-[32px]",
    "lg:leading-[7rem]",
    "lg:leading-[161%]",
    "!text-[70px]",
    "hover:bg-transparent",
    "hover:text-theme-red",
    "hover:border-theme-red",
    "text-theme-red",
    "bg-theme-red",
    "border-theme-red",
  ],
  theme: {
    screens: {
      xs: "320px",
      sm: "375px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      fontSize: {
        "xxs-h1": ["72px"],
        "xs-h1": ["60px"],
        "sm-h1": ["40px"],
        "md-h1": ["60px"],
        "lg-h1": ["48px"],
        "xl-h1": ["130px"],
        "xs-h2": ["32px"],
        "md-h2": ["36px"],
        "lg-h2": ["38px"],
        "xl-h2": ["40px"],
        "xs-h3": ["16px"],
        "lg-h3": ["32px"],
        "xs-h4": ["16px"],
        "lg-h4": ["24px"],
        "xlg-h4": ["28px"],
        "md-h4": ["22px"],
        "sm-h5": ["18px"],
        "xs-h5": ["13px"],
        "xs-h6": ["10px"],
        button: ["13px", { letterSpacing: "0.08rem", lineHeight: "110%" }],
        "xs-accordion-button-title": ["16px", { lineHeight: "22px" }],
        "lg-accordion-button-title": ["18px", { lineHeight: "22px" }],
      },
      lineHeight: {
        h1: "110%",
        h2: "120%",
        h3: "128%",
        h4: "130%",
        h5: "160%",
        body: "140%",
      },
      letterSpacing: {
        h5: "0.06em",
        headings: "0.01em",
      },
      spacing: {
        106: "106px",
        56: "56px",
        64: "64px",
        197: "197px",
        100: "100px",
        80: "80px",
        60: "60px",
        70: "70px",
      },
      colors: {
        charcoal: "#121212",
        "light-gray": "#FBFBFB",
        "medium-gray": "#D9D9D9",
        "dark-gray": "#6A6C6D",
        "error-red": "#A82626",
        "success-green": "#1D8044",
        "focus-blue": "#2F80ED",
        "theme-red": "#D40629",
        gray: "#56595A",
      },
      maxWidth: {
        460: "28.75rem",
        "3xl": "1920px",
      },
      width: {
        42: "2.63rem",
        59: "3.688rem",
      },
      height: {
        44: "2.75rem",
      },
      opacity: {
        85: ".85",
      },
      padding: {
        "15px": "15px",
        gutter: "20px",
        "normal-gutter": "30px",
        106: "106px",
        56: "56px",
        64: "64px",
        197: "197px",
        100: "100px",
        80: "80px",
        60: "60px",
      },
      fontFamily: {
        "primary-font": ["Libre Baskerville Bold"],
        "secondary-font": ["Montserrat"],
        "tertiary-font": ["Avenir Next"],
        "quaternary-font": ["'Libre Baskerville'"],
      },
      gridTemplateColumns: {
        fluid: "repeat(auto-fill, minmax(19.06rem, 1fr))",
      },
    },
    container: {
      padding: {
        DEFAULT: "1.25rem",
        xl: "3.75rem",
        "2xl": "3.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("tailwind-scrollbar-hide")],
};
